mservices:
    image: tp33/django
    container_name: mservices
    volumes:
      - ./s_mservices:/app
    ports:
      - "8000:8000"
    command: bash -c "echo \"installing dependencies...\" && 
                pip install pyyaml ua-parser user-agents &&
                pip install django-user-agents &&
                echo \"starting micro services server...\" &&
                python manage.py runserver 0.0.0.0:8000"