mservices:
    image: tp33/django
    container_name: mservices
    volumes:
      - ./s_mservices:/app
    ports:
      - "8000:8000"
    command: bash -c "echo \"starting micro services server...\" && 
                python manage.py runserver 0.0.0.0:8000"